### ISSUE TITLE
[1.0.24] checkbox group error->  flux.js: Uncaught TypeError: (value || []).map is not a function

### ISSUE THREAD

**Issue by lotje-kinable** [livewire/flux#723]
Hi! 👋

After upgrading to 1.0.24 I get the error "flux.js?id=7cb500c8:2087 Uncaught TypeError: (value || []).map is not a function"
while using a checkbox group. 

![Image](https://github.com/user-attachments/assets/8cc19db5-deba-40f5-89d1-1af357870fac)

```
<?php
use Livewire\Volt\Component;

new class extends Component {
    public $options = "all";
}; ?>

<div class="space-y-28">

    <flux:checkbox.group wire:model.change="options" label="Select your options">
        <flux:checkbox value="all" label="All options" />
        <flux:checkbox value="true" label="True options" />
        <flux:checkbox value="false" label="False options" />
    </flux:checkbox.group>

</div>

```

I love Flux 💯%!
Thanks!

**Comment by jeffchown** [comment]
@lotje-kinable Here too.  I assume it has something to do with this update:
`Fix checkbox.all not being set on page initialization - ref` https://github.com/livewire/flux/issues/632

**Comment by calebporzio** [comment]
Ah thanks for the catch. In general, you should use arrays for your checkbox group livewire property values. I fixed this though - will release shortly

**Comment by lotje-kinable** [comment]
@calebporzio I changed my existing radio group to a checkbox group in my flux playground to see if I got the same error outside of the project and I didn't think of to change it to an array! Nice of you implement it though! 

I checked the docs again, and maybe that information is relevant enough to add it here: [Checkbox group](https://fluxui.dev/components/checkbox#checkbox-group)

Personally I miss a little Livewire in the code snippets, but I understand if that is not going to be added or at least not a priority!

Thanks, Caleb!! 

ps. @jeffchown thanks for checking!
