### ISSUE TITLE
Toast error after v2.2.5 update

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#1945]
### Flux version

v2.3.2

### Livewire version

v.3.6.4

### Tailwind version

v.4.1.13

### Browser and Operating System

Safari on macOS

### What is the problem?

After updating to v2.2.5 Flux toasts fail to render when triggered from Livewire actions or client-side calls.

Errors seen:
1. click: NotSupportedError: Element does not have the popover attribute

further clicks: TypeError: existingToast.destroyToast is not a function. (In 'existingToast.destroyToast()', 'existingToast.destroyToast' is undefined)

### Code snippets to replicate the problem

```
<?php

use Livewire\Volt\Component;
use Flux\Flux;

new class extends Component {
    public function ping(): void
    {
        Flux::toast('Your changes have been saved.');
    }
    public function render(): mixed
    {
        return view('livewire.test-toast')->layout('layouts.app');
    }
}; ?>

<div class="min-h-[40vh] flex items-center justify-center p-6">
    <div class="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-6 space-y-4 text-center shadow-sm">
        <h1 class="text-lg font-semibold">Flux Toast Test</h1>
        <div class="flex items-center justify-center gap-3">
            <flux:button variant="filled" wire:click="ping">Server-Toast</flux:button>
            <flux:button variant="outline" x-on:click="$flux.toast('Your changes have been saved.')">Client-Toast</flux:button>
        </div>
    </div>
</div>


```

### Screenshots/ screen recordings of the problem

<img width="1535" height="562" alt="Image" src="https://github.com/user-attachments/assets/63d330eb-8347-45da-9833-5b98f6e68a50" />

### How do you expect it to work?

Toasts render reliably from both Livewire actions and client-side calls

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@DonCamillo11 I tried your snippet with Flux v2.3.2 and both buttons work properly for me.

Have you run `php artisan view:clear` and `npm run build` since updating Flux?
Have you customized any of the Flux components?

**Comment by DonCamillo11** [comment]
Thanks, missed to use `php artisan view:clear`

**Comment by jeffchown** [comment]
Great!  Glad that fixed it.  You're welcome, @DonCamillo11
